import { dimensions } from './dimensions.js';

export const questions = {
	[dimensions['Identity and Values']]: [
		'What values are most important to you in life?',
		'How would you describe your personal identity in a few words?',
		'What cultural or personal beliefs shape your view of the world?',
		'How do you determine what’s “right” or “wrong” in difficult decisions?',
		'Which values guide your interactions with others?',
		'How do you reconcile different parts of your identity (e.g., cultural, professional)?',
		'In what ways have your values evolved over time?',
		'How do you want others to remember your core values or identity?',
	],
	[dimensions['Key Experiences']]: [
		'What are some major milestones in your life so far?',
		'How have these experiences shaped who you are today?',
		'Which life events challenged your worldview the most?',
		'What moments have taught you the most about resilience?',
		'Are there any accomplishments that you hold especially close?',
		'How have setbacks changed your approach to life and growth?',
		'What have been your most transformative learning experiences?',
		'Which personal challenges are you most proud of overcoming?',
	],
	[dimensions['Creative Drive']]: [
		'What role does creativity play in your life?',
		'How do you express yourself creatively, whether in work or personal pursuits?',
		'What inspires your creative process or sparks your imagination?',
		'How does creativity influence your approach to problem-solving?',
		'Are there specific projects that have been meaningful for you creatively?',
		'What creative goals do you have, if any?',
		'How do you deal with creative blocks or periods of low inspiration?',
		'If there were no limits, what creative project would you pursue?',
	],
	[dimensions['Family Connections']]: [
		'How would you describe your family relationships?',
		'In what ways has your family shaped your beliefs or identity?',
		'How do family expectations influence your personal and professional goals?',
		'What values did you inherit from your family that you still hold today?',
		'Are there areas where you feel differently from your family’s views?',
		'How has your family supported or challenged your growth?',
		'In what ways do you see your family influencing your future plans?',
		'What kind of legacy do you want to leave for the next generation?',
	],
	[dimensions['Mental Health']]: [
		'What role does mental health play in your life currently?',
		'How do you recognize when your mental health needs attention?',
		'What are some strategies you find helpful in managing stress or low energy?',
		'How do periods of high or low energy affect your motivation and goals?',
		'In what ways has your understanding of mental health evolved over time?',
		'How do you balance ambition with the need for rest and recovery?',
		'What are your biggest challenges when it comes to mental well-being?',
		'How do you wish to grow in your approach to mental health and self-care?',
	],
	[dimensions['Motivation Growth']]: [
		'What are your biggest motivations in life?',
		'How do you define growth for yourself?',
		'What areas of your life are you most focused on improving?',
		'How do you handle setbacks when striving for your goals?',
		'In what ways do you balance personal well-being with your ambitions?',
		'How do you motivate yourself during low-energy phases?',
		'Are there specific habits that help you keep moving forward?',
		'How would you like to evolve in terms of motivation and growth?',
	],
	[dimensions['Setbacks Wins']]: [
		'How do you view success and failure in your life?',
		'How often do you take time to celebrate your achievements?',
		'What are some of your most memorable successes or wins?',
		'How do you process setbacks or disappointments?',
		'In what ways has failure helped you grow?',
		'How do you balance the need for productivity with the need to recharge?',
		'What small steps help you build momentum toward bigger goals?',
		'How would you like to change your approach to setbacks and wins?',
	],
	[dimensions['Faith Philosophy']]: [
		'How would you describe your spiritual or philosophical beliefs?',
		'What role does faith or philosophy play in your everyday life?',
		'How do these beliefs guide your decisions or interactions?',
		'In what ways do they shape your sense of purpose?',
		'How do you integrate your beliefs with modern life challenges?',
		'What are the values or principles you hold most sacred?',
		'How has your faith or philosophy evolved over time?',
		'What legacy do you want your beliefs to leave behind?',
	],
};
